# S3 bucket name
s3_bucket: "s3://czb-tabula-sapiens"

# List of input files to download from the bucket,
# grouped by name (used to name the sourmash outputs)
input_file_groups:
  - "TSP12_Heart_Atria_10X_1_1_S13_L003":
    - "TabulaSapiens_v2/TSP12/fastqs/10X/TSP12_Heart_Atria_10X_1_1/TSP12_Heart_Atria_10X_1_1_S13_L003_R1_001.fastq.gz"
    - "TabulaSapiens_v2/TSP12/fastqs/10X/TSP12_Heart_Atria_10X_1_1/TSP12_Heart_Atria_10X_1_1_S13_L003_R2_001.fastq.gz"

# Sourmash parameter k
sourmash_ks:
  - 21
  - 31
  - 51
